name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Upload Release Binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Validate tag creator
        run: |
          echo "🔒 Tag pushed by: ${{ github.actor }}"
          ALLOWED_USERS="satnamSandhu2001"

          if ! echo "$ALLOWED_USERS" | grep -qw "${{ github.actor }}"; then
            echo "❌ Unauthorized tag creator: ${{ github.actor }}"
            exit 1
          fi
          echo "✅ Authorized"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Build binaries
        run: make release

      - name: Create GitHub Release & Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            dist/stackjet-linux-amd64
            dist/stackjet-linux-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
